scrapper_info = [
    {
        "path":[ 
                    {
                        "tag":"h4",
                        "attributes":{
                            "id":"title"
                        }
                    },
                    {
                        "tag":"span",
                        "attributes":{
                            "id":"productTitle"
                        }
                    }
                ],
        "extract":0,
        "name":"title"
    },        
    {
        "path":[
                    {
                        "tag":"div",
                        "attributes":{
                            "id":"bylineInfo"
                        }
                    },
                    {
                        "tag":"a",
                        "attributes":{
                            "class":"a-link-normal"
                        }
                    }
                ],
        "extract":0,
        "name":"author"
    },
    {
        "path":[
                    {
                        "tag":"div",
                        "attributes":{
                            "data-audioid":"audImgSample"
                        }
                    }
                ],
        "extract":1,
        "name":"audio"
    }
]
